### ISSUE TITLE
Build Python 32 bit on Linux 64 bits

### ISSUE THREAD

**Issue by alexsilva** [python-cmake-buildsystem/python-cmake-buildsystem#102]
```
cmake -DCMAKE_C_FLAGS=-m32 -DCMAKE_EXE_LINKER_FLAGS=-m32 -DCMAKE_INSTALL_PREFIX:PATH=/home/user/src/python-install ../python-cmake-buildsystem
```

I tried with the following options, but did not succeed

```
/home/user/src/Python-2.7.8/Include/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
```

I can not understand what the problem.

**Comment by jcfr** [comment]
@alexsilva Cross-compilation support has just been integrated.

There is now continuous integration against toolchain [linux-x86](https://github.com/thewtex/cross-compilers/tree/master/linux-x86)

See https://open.cdash.org/index.php?project=CPython#/#Circle-CI_[Latest]

Let us know if you still have issue cross-compiling.

Cc: @thewtex
