### ISSUE TITLE
Installation of tests despite BUILD_TESTING=OFF

### ISSUE THREAD

**Issue by adrianbroher** [python-cmake-buildsystem/python-cmake-buildsystem#110]
When installing python via `make install` the current master of python-cmake-buildsystem installs the python unit test in LIBDIR.  I would expect that this shouldn't be the case.

To reproduce use this [CMakeLists.txt] file. Invoke it with `cmake ..` in a separate build directory.

[CMakeLists.txt]: https://gist.githubusercontent.com/adrianbroher/0e24b4d4af963187e0b1/raw/2f34a72f044d12eb644632bec3f2dec6bfb895ce/CMakeLists.txt

**Comment by jcfr** [comment]
Thanks for the detailed report :+1: 

A pull request will be pushed shortly.

**Comment by jcfr** [comment]
Et voila. See #111 

Let me know if that works as expected.

**Comment by adrianbroher** [comment]
After two failed attempts of building from python-cmake-buildsystem/python-cmake-buildsystem:master (sometimes it's better to read the actual responses **more thoroughly**) I can confirm that your branch works for me as I would expect.  Thanks for fixing this.

**Comment by jcfr** [comment]
Thanks for checking.
