### ISSUE TITLE
Why favour BUILD_{SHARED,STATIC} over BUILD_SHARED_LIBS?

### ISSUE THREAD

**Issue by adrianbroher** [python-cmake-buildsystem/python-cmake-buildsystem#121]
I'm wondering why the project allows to build users the shared and static variant at the same time using two non-standard variables to switch on/off the static or shared build.

Also  I can't think of a good reason why a regular user of this project would need to build the library shared and static at the same time.

Digging through history does give me the impression that the first implementer wasn't aware of the existence of BUILD_SHARED_LIBS.

**Comment by jcfr** [comment]
Hi, 

As you discovered, this was a decision of the first implementer.

Since it is possible to build `libpython` statically while having the module built dynamically, I would prefer we do not use `BUILD_SHARED_LIBS` (plural form). Instead we could have a single option named `BUILD_SHARED_LIBPYTHON`.

Thanks
Jc

**Comment by adrianbroher** [comment]
Given the context of your suggestion is reasonable.  I suggested `BUILD_SHARED_LIBS` just because it is the standard CMake variable for controlling static/shared builds but I'm happy with any idea that makes this part of the CMake files a bit simpler.  Would you accept PRs tackling this feature request?

**Comment by jcfr** [comment]
Now that the recent work has been integrated. A PR would be great. What do you think of the name `BUILD_SHARED_LIBPYTHON` for the option ? Set to `OFF` by default.

To ensure existing integration are not broken, I suggest you initialize the default for `BUILD_SHARED_LIBPYTHON` using the _older_ option.

Thanks

**Comment by adrianbroher** [comment]
> What do you think of the name BUILD_SHARED_LIBPYTHON for the option ?

I'm fine with the name.

> To ensure existing integration are not broken, I suggest you initialize the default for BUILD_SHARED_LIBPYTHON using the older option.

Do you think something like that is sufficient?

```cmake
option(BUILD_LIBPYTHON_SHARED "Build libpython as a shared library" OFF)

# …

if((DEFINED BUILD_SHARED) OR (DEFINED BUILD_STATIC))
  message(WARNING "Using deprecated options `BUILD_SHARED` or `BUILD_STATIC`, please change your build script to use `BUILD_LIBPYTHON_SHARED` instead")
  if(BUILD_STATIC)
    set(BUILD_LIBPYTHON_SHARED OFF CACHE BOOL "Intialized from `BUILD_STATIC` (deprecated)" FORCE)
  endif()
  if(BUILD_SHARED)
    set(BUILD_LIBPYTHON_SHARED ON CACHE BOOL "Intialized from `BUILD_SHARED` (deprecated)" FORCE)
  endif()
endif()
```

**Comment by jcfr** [comment]
re https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/issues/121#issuecomment-209356186

That is the idea. I just pushed a PR implementing the change. Let me know what you think.

Thanks
Jc
