### ISSUE TITLE
Make Python 3 the default

### ISSUE THREAD

**Issue by thewtex** [python-cmake-buildsystem/python-cmake-buildsystem#145]
The future is now!

The default version in the `CMakeLists.txt` needs to be updated and the README also.

**Comment by jcfr** [comment]
:+1: 

Changing these lines would do it: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/c25eb7c4bc4e18050e91129f81693b7d5c32f503/CMakeLists.txt#L3-L5

**Comment by dbrnz** [comment]
Better still, instead of setting separate MAJOR/MINOR/PATCH versions why not set simply set the version as a string by replacing lines three to five of `CMakeLists.txt` with the following?

```
set(PYTHON_VERSION "3.5.2")

string(REPLACE "." ";" VERSION_LIST ${PYTHON_VERSION})
list(GET VERSION_LIST 0 PY_VERSION_MAJOR)
list(GET VERSION_LIST 1 PY_VERSION_MINOR)
list(GET VERSION_LIST 2 PY_VERSION_PATCH)
```

**Comment by jcfr** [comment]
> why not set simply set the version

This was done in 0398f0e
