### ISSUE TITLE
Cannot include importlib.h

### ISSUE THREAD

**Issue by jvtrudel** [python-cmake-buildsystem/python-cmake-buildsystem#177]
On windows + qtcreator IDE + MVSC 2015 compiler.
With BUILD_LIBPYTHON_SAHRED=ON and USE_LIB_64=ON

    D:\1-build-dev\Python-3.5.2\Python\frozen.c(5): fatal error C1083:
    Cannot open include file: 'importlib.h': No such file or directory

Probably an include_directories missing somewhere...

**Comment by jvtrudel** [comment]
importlib.h is indeed present in imported python sources and include_directories points to it. I should miss something.

**Comment by jvtrudel** [comment]
I was wrong, importlib.h is not in the sources (I confused it with import.h ...). It should be generated at compile time, but CMAKE_CROSSCOMPILING_EMULATOR needed in the build process is apparently not set.

**Comment by jvtrudel** [comment]
I would need help to solve that, I have no experience with cross-compiling. 

  - How come we need to cross-compile? In that case, is is related to platform cross-compilation or does it somehow transform *_bootstrap.py* into *importlib.h*?
  - Which cross-compiler should I use?
  - Is it (another) window-msvc specific fail? Or should I simply just configure correctly for cross-compilation?

**Comment by thewtex** [comment]
A cross-compiler is not necessary -- the `CMAKE_CROSSCOMPILING_EMULATOR` variable is there in case we are are cross compiling.  In fact, if newer CMake is available, I think we can change

```
${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:_freeze_importlib>
```

to

```
_freeze_importlib
```

thanks to a patch by @jcfr that has been integrated into CMake.


@jvtrudel Experimentation with the build and other CMake generators may help.

**Comment by jvtrudel** [comment]
Thanks @thewtex . Indeed, it works perfertly with ````_freeze_importlib````.  But it still fail without it.

Should we patch it with something like 

    if(CMAKE_CROSSCOMPILING)
        ${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:_freeze_importlib>
    else()
        _freeze_importlib
    endif()
?

**Comment by thewtex** [comment]
@jvtrudel Yes, that's a good idea. Our `cmake_minimum_required` version is not new enough to just use `_freeze_importlib` on its own.

**Comment by jvtrudel** [comment]
@thewtex  I'll make a pull request  to fix it tomorrow. 

2 more questions:

  - what is the integration process? I made a very basic pull request yesterday (#176). It haev been accepted but its not merged yet. Who is responsible for merging and will it be merge in master or do we wait for the next release?
  - I'm still not able to compile python with this setup. I will need the pending (almost solved) issue #153 to compile ````python3stub.lib````.  How to proceed to have that merged?

**Comment by thewtex** [comment]
Great, thanks @jvtrudel .

Only @jcfr currently has merge abilities, so we have to wait for him.

**Comment by jvtrudel** [comment]
For  compactness of the code, I tried that
````
if(CMAKE_CROSSCOMPILING AND CMAKE_CROSSCOMPILING_EMULATOR) # set command for importlib generation
    set(freeze_importlib_command "${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:_freeze_importlib>")
else()
    set(freeze_importlib_command _freeze_importlib)
endif()

add_custom_command(
  OUTPUT ${LIBPYTHON_FROZEN_SOURCES}
  COMMAND ${freeze_importlib_command}
        ${SRC_DIR}/Lib/importlib/_bootstrap_external.py
        ${SRC_DIR}/Python/importlib_external.h
  COMMAND ${freeze_importlib_command}
        ${SRC_DIR}/Lib/importlib/_bootstrap.py
        ${SRC_DIR}/Python/importlib.h
  DEPENDS
    _freeze_importlib
    ${SRC_DIR}/Lib/importlib/_bootstrap_external.py
    ${SRC_DIR}/Lib/importlib/_bootstrap.py
)
````

But it doesn't work... Have you an idea why?

**Comment by thewtex** [comment]
For the fix, it may have to do with the quotes.

Another approach for the issue: we may be having trouble with the generator expression and the generator that is being used. CMake best practice is to not use a generator expression for an `add_custom_command` argument.

Since the automatic addition of `CMAKE_CROSSCOMPILING_EMULATOR` [was added in CMake 3.6](https://cmake.org/cmake/help/v3.7/release/3.6.html), we could change the command to just

```
_freeze_importlib
```

and require `cmake_minimum_required` version to be 3.6.0 if `CMAKE_CROSSCOMPILING`.

@jcfr thoughts?

**Comment by jvtrudel** [comment]
ok. @thewtex  I'll implement taht in the pull request #178  next week.

**Comment by jvtrudel** [comment]
I close that issue for further discussions, see #178
