### ISSUE TITLE
.gitignore ignores cmake/lib

### ISSUE THREAD

**Issue by CFSworks** [python-cmake-buildsystem/python-cmake-buildsystem#187]
There's a directory labeled "lib" located at `python-cmake-buildsystem/cmake/lib`, however the .gitignore file is causing this to be ignored.

**Comment by jcfr** [comment]
Thanks for the report and apologize for the late reply.

How could I reproduce the problem ?

I tried adding a file to the cmake/lib folder and it is properly detected.

**Comment by isaachier** [comment]
I think the issue is the use of `lib` in `.gitignore`. Try `/lib` instead.

**Comment by jcfr** [comment]
@isaachier  Thanks for the note.

Out of curiosity, did you manage to reproduce the problem ?

**Comment by isaachier** [comment]
No sorry, just noticed the patterns in the `.gitignore` would do that. From Git's gitignore docs:

> For example, "**/foo" matches file or directory "foo" anywhere, the same as pattern "foo". 

https://git-scm.com/docs/gitignore
