### ISSUE TITLE
Problems building Python 3.5.2 with cmake using the nmake generator

### ISSUE THREAD

**Issue by SJR66** [python-cmake-buildsystem/python-cmake-buildsystem#194]
[cmake-bug-report.txt](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/files/1431986/cmake-bug-report.txt)

Summary:

- Using the Visual Studio 2015 generator to build from inside the Visual Studio 2015 IDE works fine.
- Using the nmake generator from a Visual Studio command prompt fails.

This is unfortunate when integrating Python 3.5.2 into a superbuild.

See attached report for detailed step-by-step instructions on how to reproduce.

**Comment by jcfr** [comment]
Thanks for the details report 👍 

Will follow up shortly with an update.

**Comment by jcfr** [comment]
### Issue

It looks like you are configuring using the NMake generator from a regular windows command line terminal.

Doing so, CMake is not able to understand which version of visual studio compiler to use.

### Solution 

Consider setting the environment first following instruction like this one:
https://stackoverflow.com/questions/31262342/cmake-g-ninja-on-windows-specify-x64#31589526

If you entire project is built using NMake generator, you could call the script before configuring the top-level project.


### Improved integration

1. In case you need to drive part of your build using NMake generator and other using other generator,  here is a module that we are working to upstream:

https://github.com/Slicer/Slicer/blob/master/CMake/FindVcvars.cmake


2. While building python doesn't take a lot of time, if the remaining of your project is larger, you could also consider using Ninja generator.


Let me know if you have any other questions, 
Jc

**Comment by jcfr** [comment]
Closing. 

Please, create a new issue if you still have problem building the project.

**Comment by jcfr** [comment]
This was likely fixed by:
* https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/240
