### ISSUE TITLE
socket module not built when cross compiling with mingw

### ISSUE THREAD

**Issue by woggioni** [python-cmake-buildsystem/python-cmake-buildsystem#200]
Compiling with latest mingw-w64 (GCC 7.2.0) from archlinux, the build runs but the socket module is not built: when imported from the interpreter it gives this error:
```
>>> import socket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Z:\home\woggioni\build\python-cmake-buildsystem\build\Lib\socket.py", line 47, in <module>
    import _socket
ImportError: No module named _socket
```

**Comment by oggio88** [comment]
I managed to enable the socket module setting `BUILTIN_SOCKET=ON` in cmake cache, but stil I do not understand why this is not enbled by default, as it is when making a native build

**Comment by jcfr** [comment]
To follow up on this, I suggest you perform  additional testing using the corresponding images maintained in dockcross. See https://github.com/dockcross/dockcross#summary-cross-compilers

Relevant images are the following:

| Image name | Target arch | Compiler | Target OS | Description |
|:-------:|:--------:|:------:|:-----:|:-----:|
| dockcross/windows-shared-x86 | x86 | GCC | Windows | based on [MXE/MinGW-w64](https://mxe.cc/) with win32 threads and dynamic linking. |
| dockcross/windows-shared-x64 | x86_64 | GCC | Windows | based on [MXE/MinGW-w64](https://mxe.cc/) with win32 threads and dynamic linking. |
| dockcross/windows-shared-x64-posix | x86_64 | GCC | Windows | based on [MXE/MinGW-w64](https://mxe.cc/) with posix threads and dynamic linking. |
| dockcross/windows-static-x86 | x86 | GCC | Windows | based on [MXE/MinGW-w64](https://mxe.cc/) with win32 threads and static linking. |
| dockcross/windows-static-x64 | x86_64 | GCC | Windows | based on [MXE/MinGW-w64](https://mxe.cc/) with win32 threads and static linking. |
| dockcross/windows-static-x64-posix | x86_64 | GCC | Windows | based on [MXE/MinGW-w64](https://mxe.cc/) with posix threads and static linking. |


It may also be sensible to update the CircleCI configuration to test using the image that makes the most sense base on your use case.
