### ISSUE TITLE
No support for python 2.7.14?

### ISSUE THREAD

**Issue by johnmudd** [python-cmake-buildsystem/python-cmake-buildsystem#204]
Awesome tool.

I tried to build 2.7.14 but it was reject. The error specified 2.7.13 as the latest support. 2.7.13 will work for me. I was just curious about 2.7.14 because I see 2.7.15 mentioned in files such as CTestConfig.cmake.

John

**Comment by jcfr** [comment]
Hi @johnmudd 

Thanks for the kind word.

Would you have more details about the error ? (Which operating system, compiler, etc ...)

**Comment by jcfr** [comment]
I just got the following error:
```
CMake Error at CMakeLists.txt:203 (file):
  file DOWNLOAD HASH mismatch

    for file: [/tmp/python-cmake-buildsystem-build/../Python-2.7.14.tgz]
      expected hash: [show_progress]
        actual hash: [cee2e4b33ad3750da77b2e85f2f8b724]
             status: [0;"No error"]

```

It will be fixed shortly along with update to the continuous integration

**Comment by johnmudd** [comment]
Awesome, thanks!

**Comment by jcfr** [comment]
This PR improves the build system to give a meaningful message: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/205

```
$ cmake -DPYTHON_VERSION:STRING=2.7.14 ../python-cmake-buildsystem
-- The C compiler identification is GNU 5.2.1
-- The ASM compiler identification is GNU
[...]
-- Looking for CMake property POSITION_INDEPENDENT_CODE - found
-- Downloading https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz
CMake Error at CMakeLists.txt:204 (message):
  Selected PY_VERSION [2.7.14] is not associated with any checksum.  Consider
  updating this CMakeLists.txt setting _download_2.7.14_md5 variable
```
