### ISSUE TITLE
External Symbol Error on Visual Studio 2015

### ISSUE THREAD

**Issue by theclashingfritz** [python-cmake-buildsystem/python-cmake-buildsystem#216]
error LNK2001: unresolved external symbol __imp____pioinfo

I do not know it's cause. Any idea? (I've looked and tried fucking everything to fix it...)

**Comment by theclashingfritz** [comment]
Fixed it by removing extern __declspec(dllimport) char * __pioinfo[]; which isn't used in the patch for Visual Studio 2015

**Comment by jcfr** [comment]
Hi Dan,

Thanks for the report.

Out of curiosity, which option did you use to build python ? We could
enable it in the continuous integration settings.

Jc

**Comment by jcfr** [comment]
For reference, the patches used for [both 2.7.13 and 2.7.14](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/e5d28807ef5a94987bc0c0cf60b3f16bb60adce1/cmake/PythonApplyPatches.cmake#L92-L97) can be found here: https://github.com/python-cmake-buildsystem/cpython/commits/2.7.13-patches

**Comment by theclashingfritz** [comment]
I built 2.7.13.
