### ISSUE TITLE
Patch command not found despite being found.

### ISSUE THREAD

**Issue by adrianbroher** [python-cmake-buildsystem/python-cmake-buildsystem#218]
Hello,

the current master e5d28807ef5a94987bc0c0cf60b3f16bb60adce1 claims that there is no suitable `patch` command available, despite locating two patch applications with suitable versions right before that statement.  Looking into the code I don't see any reason why it shouldn't work.

```
-- Looking for CMake property POSITION_INDEPENDENT_CODE - found
-- SRC_DIR: /Users/travis/build/[secure]/[secure]-sdk/build/python-prefix/src/python
-- PY_VERSION: 2.7.14
-- Found Git: /Applications/Xcode.app/Contents/Developer/usr/bin/git (found version "2.3.2 (Apple Git-55)") 
-- Found Patch: /usr/local/bin/patch (found version "2.7.6") 
CMake Error at cmake/PythonApplyPatches.cmake:41 (message):
  Could NOT find a suitable version of Git or Patch executable to apply
  patches.
Call Stack (most recent call first):
  CMakeLists.txt:293 (include)
-- Configuring incomplete, errors occurred
```

The full log can be [found here with the relevant chunk highlighted](https://travis-ci.org/freeorion/freeorion-sdk/jobs/357719598#L6382-L6416).

**Comment by jcfr** [comment]
Thanks for the report.

It is strange that it reports finding both `Git` and `Patch`

```
-- Found Git: /Applications/Xcode.app/Contents/Developer/usr/bin/git (found version "2.3.2 (Apple Git-55)") 
-- Found Patch: /usr/local/bin/patch (found version "2.7.6") 
```

Based on the implementation, if `Git_FOUND` is True .. it should define the `PATCH_COMMAND` and move forward.

For some reason, `Git_FOUND` is set to `FALSE` ...

**Comment by jcfr** [comment]
I wonder if the problem is due to https://github.com/freeorion/freeorion-sdk/commit/e9c4f51f4a0c80e92b5cc4400492bb06c83e271a  ... 

Side question: in the folder [patches/python-cmake](https://github.com/freeorion/freeorion-sdk/tree/b60727f6a1e956c05c189f554e6b273aa2a849b1/patches/python-cmake), there are a lot of patches ... following the update, are they all needed ? I think we should be able to integrate most of them.

**Comment by jcfr** [comment]
Looking at the new build: https://travis-ci.org/freeorion/freeorion-sdk/jobs/357727393#L3563-L3571

It does not seem that the project is configured or built.

**Comment by adrianbroher** [comment]
> I think we should be able to integrate most of them.

*Ahem* #196 #182 

;)

But yes, you're right.  They should be integrated into upstream.  I wanted to make sure first that the updated build is working properly so I can present updated PRs.
