### ISSUE TITLE
Build problem with python-3.6.7 under Windows

### ISSUE THREAD

**Issue by ycollet** [python-cmake-buildsystem/python-cmake-buildsystem#245]
I  try to compile python using visual studio 2015 64 bits under Windows 10 in RELEASE mode.
I try to compile Python-3.6.7.
I meet two problems:
- first, the 3.6 patches doesn't apply to python-3.6.7.  So, I disabled the option PYTHON_APPLY_PATCHES=OFF
- second: during the compilation, I meet the following error:
```
[  1%] Building C object CMakeBuild/libpython/CMakeFiles/_freeze_importlib.dir/__/__/Modules/gcmodule.c.obj
gcmodule.c
D:\Projets\GIT\COE_2015_RELEASE\_dep\Py_3.6.7\src\Py\Include\pydtrace.h(11): fatal error C1083: Cannot open include file: 'pydtrace_probes.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~4.0\VC\bin\amd64\cl.exe' : return code '0x2'
Stop.
```

**Comment by ycollet** [comment]
Rebuilt from scratch and the only problem I've got now is that the patches doesn't apply
I think it's because the source dir where I build python is named "Py".
I used this short dirname because the path length was quite long and was more than 256 characters long ...
This brings problem when deleting some files.

**Comment by jcfr** [comment]
Thanks for the update.

> I used this short dirname because the path length was quite long and was more than 256 characters long

Makes sense.

> I think it's because the source dir where I build python is named "Py".

Looking into this now. 

I tried to configure source found at `D:\T\Py` and wasn't able to reproduce the problem:

```
c:\cmake-3.13.4\bin\cmake.exe -DSRC_DIR:PATH= -DBUILD_LIBPYTHON_SHARED:BOOL=1 -DPYTHON_VERSION:STRING=3.6.7 -G "Visual Studio 15 2017 Win64" -DSRC_DIR:PATH=D:\T\Py ../python-cmake-buildsystem
[...]
-- SRC_DIR: D:/T/Py
-- PY_VERSION: 3.6.7
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.11.0.windows.1")
--
-- Applying '3.6/0001-Prevent-incorrect-include-of-io.h-found-in-libmpdec-.patch'
-- Applying '3.6/0001-Prevent-incorrect-include-of-io.h-found-in-libmpdec-.patch' - done
-- Applying '3.6/0002-Prevent-duplicated-OverlappedType-symbols-with-built.patch'
-- Applying '3.6/0002-Prevent-duplicated-OverlappedType-symbols-with-built.patch' - done
-- Applying '3.6/0003-mpdecimal-Export-inlined-functions-to-support-extens.patch'
-- Applying '3.6/0003-mpdecimal-Export-inlined-functions-to-support-extens.patch' - done
-- Applying '3.6/0004-Fix-Windows-build-of-Python-for-latest-WinSDK.patch'
-- Applying '3.6/0004-Fix-Windows-build-of-Python-for-latest-WinSDK.patch' - done
--
-- Skipping patches: Directory 'D:/T/python-cmake-buildsystem/patches/3.6.7' does not exist
-- Skipping patches: Directory 'D:/T/python-cmake-buildsystem/patches/3.6.7/Windows' does not exist
-- Skipping patches: Directory 'D:/T/python-cmake-buildsystem/patches/3.6.7/Windows-MSVC' does not exist
-- Skipping patches: Directory 'D:/T/python-cmake-buildsystem/patches/3.6.7/Windows-MSVC/1915' does not exist
-- The CXX compiler identification is MSVC 19.15.26730.0
[...]
```

For reference, this is where the build system check if a patch has been applied or not:

https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/274bfe64582ffba0e489acfce8d2d5b05bdd1738/cmake/PythonApplyPatches.cmake#L58-L69

**Comment by jcfr** [comment]
Could you confirm that `PYTHON_APPLY_PATCHES` is `ON` ?

**Comment by ycollet** [comment]
Now, to be able to build python using cmake, I explicitely set PYTHON_APPLY_PATCHES to OFF ...

**Comment by ycollet** [comment]
```
mkdir PYTMP
cd PYTMP
# unzip Python-3.6.7.tar.gz into this directory
move Python-3.6.7 Py
git clone https://github.com/python-cmake-buildsystem/python-cmake-buildsystem pybuild
xcopy pybuild Py /S /E
cd Py
mkdir build
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=c:/python-dev -G "NMake Makefiles" ..
nmake
```
This works fine for me too ... Strange ...
I build the python project using the "externalproject" command from cmake. I will investigate ... Sorry for the nosie

**Comment by ycollet** [comment]
Here is the message I've got:
```
SRC_DIR: D:/Projets/GIT/COE_2015_DEBUG/_dep/Py_3.6.7/src/Py
PY_VERSION: 3.6.7
Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.16.1.windows.4") 

Applying '3.6/0001-Prevent-incorrect-include-of-io.h-found-in-libmpdec-.patch'
Applying '3.6/0001-Prevent-incorrect-include-of-io.h-found-in-libmpdec-.patch' - failed
CMake Error at cmake/PythonApplyPatches.cmake:86 (message):
  

  error: patch failed: Modules/_decimal/libmpdec/io.c:38

  error: Modules/_decimal/libmpdec/io.c: patch does not apply
Call Stack (most recent call first):
  cmake/PythonApplyPatches.cmake:100 (_apply_patches)
  CMakeLists.txt:283 (include)
```

**Comment by ycollet** [comment]
OK. I think I found the problem:
I was in the build directory and I performed a "cmake ." to restart the configuration. And now, the patch doesn't apply because they are already applied ...

**Comment by jcfr** [comment]
Closing. Last comment seems to indicate the issue has been addressed. 

If there are still problems, consider creating a new issue.
