### ISSUE TITLE
Build of Python 2.7.11 fails with VS2015

### ISSUE THREAD

**Issue by khainke** [python-cmake-buildsystem/python-cmake-buildsystem#249]
The build for Python 2.7.11 with VS 14 2015 fails, probably because the patches from #161 are not applied / only applied for Python >= 2.7.13. I changed the lines 92-97 in the cmake/PythonApplyPatches.cmake to apply them anyways. Then the build worked for me. Dont know about possible side-effects though.

**Comment by blacklat** [comment]
forget this project, you'll waste more time trying to fix their bugs than trying to do that you want...

**Comment by jcfr** [comment]
Thanks for the report :pray:

> I changed the lines 92-97 in the cmake/PythonApplyPatches.cmake to apply them anyways

Would you mind creating a pull request with the corresponding changes ?

**Comment by khainke** [comment]
[This commit](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/commit/cf6a98253daad6872e85836f380485c6f0535971) propably did similar changes and probably fixed the issue already, i can't rly test it, but it is strongly implied by the commit message.

**Comment by khainke** [comment]
Sorry for the closing-and-reopening-confusion, there is quite some time passed, since i faced the problem (btw. at that time it was because i wanted to build that specific python for Maya). Also the PythonApplyPatches.cmake changed since then, but if i recall correctly i just applied the 2.7.13 patches for 2.7.11 and 2.7.12. And as i said, i have no idea, if this is valid. I created a draft pull request, but i can't test it right now, might get to it at the weekend.
