### ISSUE TITLE
Python 3.7.6 WORKING on Linux and Windows

### ISSUE THREAD

**Issue by dand-oss** [python-cmake-buildsystem/python-cmake-buildsystem#255]
Python 3.7.6 WORKING on Linux and Windows for release and debug.

Need to finish support for all previous python versions

PR #254 
PR #264

**Comment by RussellHaley** [comment]
Hi, 

First, thank you for this amazing cmake build repo. I'm just starting into cmake and it's been quite the journey. Currntly I'm trying to cross compile python for Windows using llvm-mingw on FreeBSD.  I added (pillford) a toolchain file called mingw-cross.cmake:

``` cmake
# Set up the cross-compiler for llvm-mingw or vanilla gcc/mingw64

set(CMAKE_SYSTEM_NAME Windows)
set(MINGW TRUE)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(CYGWIN OR WIN32)
    set(UTIL_SEARCH_CMD where)
elseif(UNIX OR APPLE)
    set(UTIL_SEARCH_CMD which)
endif()

#~ 64 bit llvm arch NOTE: This may be unnecessary - I don't know if CMAKE_SYSTEM_PROCESSOR will work or not...
set(CROSS_ARCH x86_64)

#~ 32 bit llvm arch
#~ set(CROSS_ARCH i686)
#~ set(TOOLCHAIN_PREFIX arm-none-eabi-)
set(TOOLCHAIN_PREFIX ${CROSS_ARCH}-w64-mingw32-)

execute_process(
        COMMAND ${UTIL_SEARCH_CMD} ${TOOLCHAIN_PREFIX}gcc
        COMMAND_ECHO STDOUT
        OUTPUT_VARIABLE BINUTILS_PATH
        OUTPUT_STRIP_TRAILING_WHITESPACE
)

message(STATUS "Bin utils: ${BINUTILS_PATH}")
get_filename_component(MINGW_TOOLCHAIN_DIR ${BINUTILS_PATH} DIRECTORY)

message(DEBUG "TOOLCHAIN PREFIX:  ${MINGW_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}")

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)
set(CMAKE_OBJCOPY ${MINGW_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_OBJDUMP ${MINGW_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}objdump CACHE INTERNAL "objdump tool")
set(CMAKE_SIZE_UTIL ${MINGW_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")


set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```

After cmake finishes, I initially get an error `Must define SIZEOF_WCHAR_T`. I patched `Python-3.6.7/Include/unicodeobject.h` with `#define SIZEOF_WCHAR_T 2` ,  as noted here: http://trac.wxwidgets.org/ticket/12013

At this point the build runs for quite some time, but I end up with errors about a missing importlib.h. I've lost the build output at the moment but will get you a full build output if you need it. None the less, when I re-run the build I get a new error:

```
ninja: error: dependency cycle: ../Python-3.6.7/Python/importlib.h -> CMakeBuild/libpython/_freeze_importlib.exe -> CMakeBuild/libpython/CMakeFiles/_freeze_importlib.dir/__/__/Python-3.6.7/Python/frozen.c.obj -> ../Python-3.6.7/Python/importlib.h
```

I searched the interweb for "importlib.h" and found a generated file in the cpython git repo; then it all fell together. It seems Importlib.h is generated by an executable _freeze_importlib, that clearly can't run if I'm cross building. The error above seems to be telling me that this cross build won't work?

If I can get this to work, I can then add this python build system to the llvm-mingw build for windows to add python support to the debugger lldb. I will then have a complete C/C++ toolchain for windows (http://www.winlua.net)!
