### ISSUE TITLE
PYTHONFRAMEWORK mismatch

### ISSUE THREAD

**Issue by concatime** [python-cmake-buildsystem/python-cmake-buildsystem#293]
Hi,
I upgraded today from d7e201c3308c51eb1766701cbe615f38e4762274 to 56409629cf1fec75c7cf1a6209076594d3aa2290 (master ATM).
When building kitty using the newly built python, I faced [this](https://github.com/kovidgoyal/kitty/blob/v0.21.2/setup.py#L205) exception.
After digging, I realized that the value of `PYTHONFRAMEWORK` is different between the two commits.
Empty for the [former](https://builds.sr.ht/~iemaghni/job/669122#task-build-1498) and `""` for the [latter](https://builds.sr.ht/~iemaghni/job/669117#task-build-1497).
The command to reproduce is simply:
```sh
python -c 'import sysconfig;print(sysconfig.get_config_var("PYTHONFRAMEWORK"))'
```
Thank you :)
(and truly thank you for this project, `cpyton`'s autoconf is a nightmare.)

**Comment by concatime** [comment]
Another issue, probably related (`sysconfig` still), using the latter commit, I get this warning from a recent `pip`:
```
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/build/.local/lib/python3.6/site-packages
  sysconfig: /home/build/.local/lib/python/site-packages
  WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/build/.local/lib/python3.6/site-packages
  sysconfig: /home/build/.local/lib/python/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
```
Reproducible bug: [before](https://builds.sr.ht/~iemaghni/job/669625#task-build-1512) & [after](https://builds.sr.ht/~iemaghni/job/669629#task-build-1502).

**Comment by jcfr** [comment]
Thanks so much for the detailed report :pray: 

This explains the following warning:

```
/home/build/Python-3.7.12/Programs/python.c:15:12: warning: implicit declaration of function '_Py_UnixMain' [-Wimplicit-function-declaration]
   15 |     return _Py_UnixMain(argc, argv);
      |      
```

**Comment by concatime** [comment]
Another issue is that Python fails to compile when `LDFLAGS` contains `-Wl,-z,defs` as you can see in [this CI](https://builds.sr.ht/~iemaghni/job/671503). Tons of `undefined reference`.

**Comment by concatime** [comment]
And finally, the bug that took me LITERALLY a day to properly reproduce it in a CI, even if I’m yet able to identify why. This bug emerged when I tried to compile gobject-introspection.
When using a combination of ThinLTO and `-march=x86-64-v3 -fstack-protector-strong`. I get:
```
samu: job terminated due to signal 11: /home/build/build/tools/g-ir-scanner --output=gir/GLib-2.0.gir [...]
```
My hypothesis is that the linker segfaults when handling `-lpython3.6m`.
This issue emerged between d7e201c3308c51eb1766701cbe615f38e4762274 and 56409629cf1fec75c7cf1a6209076594d3aa2290 too.
Here are the logs: [before it worked](https://builds.sr.ht/~iemaghni/job/671506#task-build-1878), but not [after](https://builds.sr.ht/~iemaghni/job/671512#task-build-1818).
The **only** difference between the two builds is the commit hash of python-cmake-buildsystem.
