### ISSUE TITLE
Not possible to compile using intel compiler

### ISSUE THREAD

**Issue by ycollet** [python-cmake-buildsystem/python-cmake-buildsystem#40]
It's not possible to compile python using intel compiler.
This is due to the name of the python library.
Here is a patch which allows to compile python using intel compiler under windows + add a BUILTIN_ALL option which activate all builtins.

```
From f93cd14be0cd2c249e21116e5ee24b49f1de90d7 Mon Sep 17 00:00:00 2001
From: Yann Collette <ycollette.nospam@free.fr>
Date: Wed, 7 May 2014 12:15:40 +0200
Subject: [PATCH 1/1] enable compilation with intel under windows + add
 builtin_all option

---
 CMakeLists.txt         |  5 +++--
 cmake/Extensions.cmake | 15 ++++++++++-----
 2 files changed, 13 insertions(+), 7 deletions(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index cf0d417..b844579 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -15,9 +15,9 @@ project(Python${PY_VERSION_MAJOR}${PY_VERSION_MINOR} C)
 
 # This is the major version number of Python
 set(LIBPYTHON_VERSION ${PY_VERSION_MAJOR}.${PY_VERSION_MINOR})
-if(MSVC)
+if(MSVC OR "${CMAKE_C_COMPILER_ID}" STREQUAL "Intel"))
     set(LIBPYTHON_VERSION ${PY_VERSION_MAJOR}${PY_VERSION_MINOR})
-endif(MSVC)
+endif()
 set(LIBPYTHON python${LIBPYTHON_VERSION})
 
 # Include helper functions
@@ -30,6 +30,7 @@ include(CTest)
 # Options
 option(BUILD_SHARED "Build a shared libpython library" OFF)
 option(BUILD_STATIC "Build a static libpython library" ON)
+option(BUILTIN_ALL  "Build all extensions as builtin"  OFF)
 option(USE_LIB64 "Search for dependencies and install to prefix/lib64 instead of prefix/lib" OFF)
 
 option(USE_SYSTEM_LIBRARIES "Use system libraries" ON)
diff --git a/cmake/Extensions.cmake b/cmake/Extensions.cmake
index 7366c99..145c0b9 100644
--- a/cmake/Extensions.cmake
+++ b/cmake/Extensions.cmake
@@ -64,11 +64,16 @@ function(add_python_extension name)
            "Controls whether the \"${name}\" extension will be built"
            ON
     )
-    option(BUILTIN_${upper_name}
-           "If this is set the \"${name}\" extension will be compiled in to libpython"
-           ${ADD_PYTHON_EXTENSION_BUILTIN}
-    )
-
+    if (BUILTIN_ALL)
+      option(BUILTIN_${upper_name}
+             "If this is set the \"${name}\" extension will be compiled in to libpython" ON}
+      )
+    else ()
+      option(BUILTIN_${upper_name}
+             "If this is set the \"${name}\" extension will be compiled in to libpython"
+             ${ADD_PYTHON_EXTENSION_BUILTIN}
+      )
+    endif ()
     # Check all the things we require are found.
     set(missing_deps "")
     foreach(dep ${ADD_PYTHON_EXTENSION_REQUIRES} ENABLE_${upper_name})
-- 
1.9.0
```

**Comment by jcfr** [comment]
Original topic published by @ycollet including Intel related changes is available here: https://github.com/jcfr/python-cmake-buildsystem/tree/win_intel_compil

@ycollet If you still have access to an Intel compiler, it would be great if you could create a new topic based of the current master.

**Comment by ycollet** [comment]
Hello,

I just tested the compilation of the current master using intel compiler (C, C++) under Windows, and it works out of the box.
I think the current changes in the master are enought to allow the compilation of python. And the interpreter works.
I haven't compiled the dependencies (Tcl/Tk, SSH, etc ...).

The command line I used:

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=d:/python-bin -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Intel/Composer XE 2013 SP1/bin/ia32/icl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Intel/Composer XE 2013 SP1/bin/ia32/icl.exe" -G "NMake Makefiles" ..
nmake
nmake install

Best regards,

YC

----- Mail original -----
De: "Jean-Christophe Fillion-Robin" <notifications@github.com>
À: "python-cmake-buildsystem/python-cmake-buildsystem" <python-cmake-buildsystem@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>
Envoyé: Mercredi 9 Septembre 2015 06:43:38
Objet: Re: [python-cmake-buildsystem] Not possible to compile using intel compiler (#40)



Original topic published by @ycollet including Intel related changes is available here: https://github.com/jcfr/python-cmake-buildsystem/tree/win_intel_compil 

@ycollet If you still have access to an Intel compiler, it would be great if you could create a new topic based of the current master.

**Comment by jcfr** [comment]
@ycollet Thanks for the quick feedback. I will then close this issue. :+1: 

Moving forward, it will be great to have a dashboard compiling and running the python test. Similar to the one reporting here: https://open.cdash.org/index.php?project=CPython

That would allow us to know when things are broken for Intel compiler on windows.

Do you think you could contribute such dashboard ? 


_Contributing a dashboard_ means that, based on your choice, your machine could either run(1)  once a night or (2) continuously (meaning that each time there are new commits on master, your machine will be building, testing and reporting back)

To help with the process, soon, I will write down the instruction to setup such a dashboard.

**Comment by ycollet** [comment]
Just a small question for the dashbord: how do you start the tests ?
We have an internal jenkins running. I think I can integrate python-cmake compilation into our jenkins.
I will the only one to have access to the results, but I can report them back to the project in case of problems.

----- Mail original -----
De: "Jean-Christophe Fillion-Robin" <notifications@github.com>
À: "python-cmake-buildsystem/python-cmake-buildsystem" <python-cmake-buildsystem@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>
Envoyé: Mercredi 9 Septembre 2015 16:00:20
Objet: Re: [python-cmake-buildsystem] Not possible to compile using intel compiler (#40)



@ycollet Thanks for the quick feedback. I will then close this issue. :+1:

Moving forward, it will be great to have a dashboard compiling and running the python test. Similar to the one reporting here: https://open.cdash.org/index.php?project=CPython 

That would allow us to know when things are broken for Intel compiler on windows. 

Do you think you could contribute such dashboard ? 

Contributing a dashboard means that, based on your choice, your machine could either run(1) once a night or (2) continuously (meaning that each time there are new commits on master, your machine will be building, testing and reporting back) 

To help with the process, soon, I will write down the instruction to setup such a dashboard.
