### ISSUE TITLE
Integrate configure check fix for HAVE_WORKING_TZSET

### ISSUE THREAD

**Issue by jcfr** [python-cmake-buildsystem/python-cmake-buildsystem#58]
See contribution from @shadowmint: https://github.com/shadowmint/cmake-python-embed-nostdlib/commit/e534afff5c035d43c585bbb733306939b3514082#diff-a9adfbd27c469a657b6c9b5a7452d74c

**Comment by jcfr** [comment]
@shadowmint For reference, your fixes related to double quotes were integrated in 2227217c2 (change related to issue #32)

**Comment by shadowmint** [comment]
:star: nice! Thanks for the heads up.

**Comment by jcfr** [comment]
As a side note that may interest you... support for python 3.5.1 has just been merged.
