### ISSUE TITLE
Update build system to support python 3.x series

### ISSUE THREAD

**Issue by jcfr** [python-cmake-buildsystem/python-cmake-buildsystem#59]
See contribution of @gongminmin here: https://github.com/gongminmin/python-cmake-buildsystem/commits/master

**Comment by thewtex** [comment]
wOOOt!

**Comment by jcfr** [comment]
Fixed in  421256b 

@gongminmin You may be interested to know that the build system now support python 3.5.1

Note that it hasn't been tested with older 3.x versions.

**Comment by gongminmin** [comment]
Wonderful! Then I may not need a fork myself. I'm using 3.5.1, too.

**Comment by jcfr** [comment]
Yeahh :+1: 

Let me know if there are any issue.

**Comment by gongminmin** [comment]
Sure. I'll try it in my project asap. Thx!

**Comment by jcfr** [comment]
@gongminmin I also invited  you to be a member of the `python-cmake-buildsystem ` team .. that way you will be notified when feedback is inquired. For example, if you have a chance, let me know what you think of #116

**Comment by gongminmin** [comment]
Sorry for the delay. I finally get some time to work on python. Your changes to support python 3.x works on Windows well! Thanks for your work.

One minor problem. If someone need to have multiple configurations a time, e.g. set CMAKE_CONFIGURATION_TYPES to "Debug;Release;RelWithDebInfo;MinSizeRel", there will be an error message from line 283 of the root CMakeLists.txt.

`set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "default" "siphash24" "fnv")`

because no CMAKE_BUILD_TYPE is defined. I don't know how to fix this so I temporary comment out this line.

Also, I tried to cross compile python to android. It fails on a try_run. I think I have a fix on that. I'll wrap it up and send out a pull request.

**Comment by jcfr** [comment]
Thanks for the feedback.

> will be an error message from line 283 of the root CMakeLists.txt.

This is now fixed in https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/commit/39371b04265d1fc25b50f8f3b2f7acbb399ad6e8

>  cross compile python to android.

PR to  improve android support are welcome.

There is also an older topic where I was working to directly compile on the android device within [termux](https://termux.com/). The topic would have to be rebased/adapted. 
See https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/commits/fix-android-build

**Comment by gongminmin** [comment]
Thanks @jcfr , the WITH_HASH_ALGORITHM fix works!

Agree that the android support is tough. Not only because the cross compiling, but also the python itself requires some modifications to get compiled for android. I'll rebase your fix-android-build to latest master locally, and try it.

**Comment by jcfr** [comment]
> the WITH_HASH_ALGORITHM fix works!

Great. Thanks for the update

> I'll rebase your fix-android-build to latest master locally, and try it.

Before spending to much time with this older topic, it may be worth using the `thewtex/cross-compiler-android-arm`  docker  image and cherry-picking/adapting only the commit that are fixing failures.

See [here](https://github.com/thewtex/cross-compilers) for more details.

**Comment by gongminmin** [comment]
Oh thanks, Currently I'm using google's android NDK as my cross platform compiler. And also I have a patch for python's source code to work with NDK. It'll submit to cpython soon.

**Comment by gongminmin** [comment]
Just push a rebased fix-android-build to my fork https://github.com/gongminmin/python-cmake-buildsystem/tree/fix-android-build.

Also I create a new branch about building python with android NDK https://github.com/gongminmin/python-cmake-buildsystem/tree/android-ndk. But it's too preliminary to PR currently.
