### ISSUE TITLE
Transfer ownership to "python-cmake-buildsystem" organization

### ISSUE THREAD

**Issue by jcfr** [python-cmake-buildsystem/python-cmake-buildsystem#63]
Hi David, 

Hope things are going well. 

To facilitate the management of the project (for example setup of continuous integration, ...) I would suggest you transfer its ownership to the `python-cmake-buildsystem` organization.

Let me know what you think, 

Thanks
Jc

**Comment by jcfr** [comment]
To all contributors @thewtex @ihnorton @jrobcary @chuckatkins @ycollet @glehmann @adrianbroher @wdicharry , to facilitate management of the project (easier setup of continuous integration, ... ), I asked @davidsansome if he could transfer the ownership of his repository to the @python-cmake-buildsystem organization I just created.

After the ownership has been transferred, I could easily setup a bot to keep http://github.com/davidsansome/python-cmake-buildsystem up-to-date. Let me know if that would be helpful.

Details about repository transfer are reported here: https://help.github.com/articles/transferring-a-repository/

Here is the plan, let me know what you think,
Jc

**Comment by thewtex** [comment]
:+1:

**Comment by jrobcary** [comment]
Sounds reasonable to me.  Pls let us know how you envision the workflow.

Best.....JRC

**Comment by ihnorton** [comment]
+1

**Comment by glehmann** [comment]
:+1:

**Comment by wdicharry** [comment]
Also fine with me, especially since I'm not really doing any work
integrating with native code anymore :-)

**Comment by davidsansome** [comment]
Sorry for the delay, I didn't notice this issue before!  Yes I agree, I've transferred the repo now: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem

**Comment by jcfr** [comment]
Thanks @davidsansome 

CI for AppVeyor and Travis is now up and going for new PRs.
