### ISSUE TITLE
Add CircleCI support

### ISSUE THREAD

**Issue by jcfr** [python-cmake-buildsystem/python-cmake-buildsystem#80]
Similarly to `appveyor` and `travis`:

* a script named `circle_dashboard.cmake` could be added to the `dashboard` branch. See https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/tree/dashboard
* a file named `circle.yml` could be added to the `master` branch. See https://circleci.com/docs/configuration for help

CircleCI has been activated and adding the missing files should now be sufficient.

See https://circleci.com/gh/python-cmake-buildsystem/python-cmake-buildsystem

**Comment by jcfr** [comment]
@thewtex Let me know if you would like to work on this :)  

Ps: Seems you didn't accept the invite to the 'python-cmake-buildsystem' organization.

**Comment by thewtex** [comment]
Super!

Yeah I missed the invite -- joined now :-). Thanks!

Please assign this one to me.

**Comment by jcfr** [comment]
CircleCI support has been added following integration of https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/commit/60c3fd0b48bd12947e2f6579a6a3a9a5629b6877 and https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/commit/14c8c57290fa2c81daa1d4ee039827a6fc03a323
