### ISSUE TITLE
Include topic branch name in Travis-CI and AppVeyor-CI CTest Build Name

### ISSUE THREAD

**Issue by thewtex** [python-cmake-buildsystem/python-cmake-buildsystem#83]
Right now they list "master" and part of the commit hash, but it would more informative to have the pull request topic branch name instead of "master".

**Comment by jcfr** [comment]
Good catch. 

That seems to be an issue with travis and appveyor ?  

In both case, we are using the env variable set by the corresponding system.

See [here](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/a41e3ad6bd164556c8b41e230b6f9c6f250ff0be/appveyor_dashboard.cmake#L9) for `APPVEYOR_REPO_BRANCH`

See [here](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/a41e3ad6bd164556c8b41e230b6f9c6f250ff0be/travis_dashboard.cmake#L11) for `TRAVIS_BRANCH`

**Comment by thewtex** [comment]
From [the travis docs](
http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables)
it looks like `TRAVIS_PULL_REQUEST` is more informative (the pull request
number).

and [the appveyor docs](http://www.appveyor.com/docs/environment-variables)
`APPVEYOR_PULL_REQUEST_TITLE` and `APPVEYOR_PULL_REQUEST_NUMBER`.

**Comment by jcfr** [comment]
Agreed. 

I guess I added this while I was directly pushing branch onto my fork before the transition to the new organization. At that time, no PR was used on my fork.

Now we have a shinny new organization, I suggest we switch the scripts `travis_dashboard.cmake` and `appveyor_dashboard.cmake` to use the env variables you referenced.

We should also make sure to only list `master` in the corresponding yml files.

**Comment by thewtex** [comment]
Ok, working on a PR :-)

**Comment by jcfr** [comment]
Tres bien. Merci

**Comment by jcfr** [comment]
For reference, see #84

**Comment by jcfr** [comment]
PR# is now displayed :+1:  That said there is a small glitch.

When the `master` branch is built, `TRAVIS_PULL_REQUEST` is set to `false` for travis and the corresponding variable for appveyor are empty. See screenshot below for an illustration.

Would it be possible to propose a follow up commit checking for these and displaying the name of the branch if a regular branch is tested ?

![screenshot from 2015-08-25 04 15 26](https://cloud.githubusercontent.com/assets/219043/9461959/4c91e00c-4ae0-11e5-8f9b-2d1bd4656b30.png)
